---
- name: Initialization
  hosts: k8s_cluster01
  become: true
  tasks:
    - name: Updates all paquets
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true
    - name: Update the /etc/hosts file with node name
      ansible.builtin.lineinfile:
        dest: "/etc/hosts"
        regexp: ".*\t{{ hostvars[item].tags.Name.split('-')[-1] }}\t{{ hostvars[item].tags.Name.split('-')[-1] }}"
        line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}\t{{ hostvars[item].tags.Name.split('-')[-1] }}\t{{ hostvars[item].tags.Name.split('-')[-1] }}"
        state: present
        backup: true
      with_items: "{{ groups['k8s_cluster01'] }}"

- name: Worker Configuration
  hosts: _Worker
  become: true
  vars:
    packages:
      - { name: yum-utils, state: latest }
      - { name: containerd.io, state: latest }
  tasks:
    - name: Add Docker repo
      ansible.builtin.shell: yum-config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo
    - name: "Install Master & Worker package"
      ansible.builtin.dnf:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      loop: "{{ packages }}"
    - name: Start Containerd service
      ansible.builtin.service:
        name: containerd
        state: started
        enabled: true
- name: Loadbalancer Configuration
  hosts: _LoadBalancer
  become: true
  tasks:
    - name: "Install Loadbalancer package"
      ansible.builtin.dnf:
        name: haproxy
        state: present
    - name: "Configure HAProxy"
      ansible.builtin.script:  files/create-haproxy.sh "192.168.56.30" "192.168.56.11" "controlplane01" "192.168.56.12" "controlplane02"
    - name: Set haproxy_connect_any flag on and keep it persistent across reboots
      ansible.posix.seboolean:
        name: haproxy_connect_any
        state: true
        persistent: true
    - name: Start HAProxy Service
      ansible.builtin.service:
        name: "haproxy"
        state: restarted
        enabled: true
        daemon_reload: true