---
- name: Kubernetes Controlplanes Provision
  hosts: _Master
  become: true
  vars:
    KUBE_VERSION: v1.29.10
    ARCH: amd64
    SERVICE_CIDR: 10.96.0.0/16
  tasks:
    - name: Download Bianries
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: /usr/local/bin/
        owner: root
        group: root
        mode: 0700
        force: false
      loop:
        - "https://dl.k8s.io/release/{{ KUBE_VERSION }}/bin/linux/{{ ARCH }}/kube-apiserver"
        - "https://dl.k8s.io/release/{{ KUBE_VERSION }}/bin/linux/{{ ARCH }}/kube-controller-manager"
        - "https://dl.k8s.io/release/{{ KUBE_VERSION }}/bin/linux/{{ ARCH }}/kube-scheduler"
        # - "https://dl.k8s.io/release/{{ KUBE_VERSION }}/bin/linux/{{ ARCH }}/kubectl"
    - name: Create Kubernetes API-Server
      vars:
        PRIMARY_IP: "{{ ansible_default_ipv4.address }}"
        CONTROL01: "{{ hostvars[groups['_Master'][0]]['ansible_default_ipv4']['address'] }}"
        CONTROL02: "{{ hostvars[groups['_Master'][1]]['ansible_default_ipv4']['address'] }}"
        LOADBALANCER: "192.168.56.30"
      ansible.builtin.script:  files/create-apiserver-service.sh "{{ PRIMARY_IP }}" "{{ CONTROL01 }}" "{{ CONTROL02 }}" "{{ LOADBALANCER }}" "{{ SERVICE_CIDR }}"
    
    - name: Create Kubernetes Controller Manager
      vars:
        POD_CIDR: 10.244.0.0/16
      ansible.builtin.script:  files/create-controller-manager-service.sh "{{ POD_CIDR }}" "{{ SERVICE_CIDR }}"
    
    - name: Create Kubernetes scheduler
      ansible.builtin.script: files/create-scheduler-service.sh

    - name: Start Kubernetes Services
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
        enabled: true
        daemon_reload: true
      loop:
        - kube-apiserver
        - kube-controller-manager
        - kube-scheduler
